### ISSUE TITLE
500 on hijack user logout

### ISSUE THREAD

**Issue by shanbady** [mitodl/mit-open#1162]
### Expected Behavior
When logging out of a hijacked user we should not encounter a 500

### Current Behavior
When attempting to logout of a hijacked user on a live environment we get the following 500:
``` Internal Server Error: /logout/
2024-06-25T16:31:40.372948+00:00 app[web.2]: Traceback (most recent call last):
2024-06-25T16:31:40.372948+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-06-25T16:31:40.372949+00:00 app[web.2]:     response = get_response(request)
2024-06-25T16:31:40.372949+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372951+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-06-25T16:31:40.372951+00:00 app[web.2]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-06-25T16:31:40.372951+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372951+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
2024-06-25T16:31:40.372952+00:00 app[web.2]:     return callback(request, *args, **kwargs)
2024-06-25T16:31:40.372952+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372952+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/newrelic/hooks/framework_django.py", line 558, in wrapper
2024-06-25T16:31:40.372952+00:00 app[web.2]:     return wrapped(*args, **kwargs)
2024-06-25T16:31:40.372952+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372953+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
2024-06-25T16:31:40.372953+00:00 app[web.2]:     return self.dispatch(request, *args, **kwargs)
2024-06-25T16:31:40.372953+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372953+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
2024-06-25T16:31:40.372954+00:00 app[web.2]:     return bound_method(*args, **kwargs)
2024-06-25T16:31:40.372954+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372954+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
2024-06-25T16:31:40.372954+00:00 app[web.2]:     response = view_func(request, *args, **kwargs)
2024-06-25T16:31:40.372954+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372954+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/auth/views.py", line 147, in dispatch
2024-06-25T16:31:40.372955+00:00 app[web.2]:     return super().dispatch(request, *args, **kwargs)
2024-06-25T16:31:40.372955+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372955+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/newrelic/hooks/framework_django.py", line 943, in wrapper
2024-06-25T16:31:40.372955+00:00 app[web.2]:     return wrapped(*args, **kwargs)
2024-06-25T16:31:40.372955+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372955+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
2024-06-25T16:31:40.372956+00:00 app[web.2]:     return handler(request, *args, **kwargs)
2024-06-25T16:31:40.372956+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372956+00:00 app[web.2]:   File "/app/authentication/views.py", line 50, in get
2024-06-25T16:31:40.372956+00:00 app[web.2]:     return redirect(self._keycloak_logout_url(user))
2024-06-25T16:31:40.372956+00:00 app[web.2]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372956+00:00 app[web.2]:   File "/app/authentication/views.py", line 34, in _keycloak_logout_url
2024-06-25T16:31:40.372957+00:00 app[web.2]:     id_token = user_social_auth_record.extra_data.get("id_token")
2024-06-25T16:31:40.372957+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.372957+00:00 app[web.2]: AttributeError: 'NoneType' object has no attribute 'extra_data'
2024-06-25T16:31:40.373015+00:00 app[web.2]: [2024-06-25 16:31:38] ERROR 81 [django.request] log.py:241 - [f7692ab5-5920-4e84-afa0-1ff4d15ef40a] - Internal Server Error: /logout/
2024-06-25T16:31:40.373015+00:00 app[web.2]: Traceback (most recent call last):
2024-06-25T16:31:40.373015+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-06-25T16:31:40.373015+00:00 app[web.2]:     response = get_response(request)
2024-06-25T16:31:40.373015+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373016+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-06-25T16:31:40.373016+00:00 app[web.2]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-06-25T16:31:40.373016+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373016+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
2024-06-25T16:31:40.373017+00:00 app[web.2]:     return callback(request, *args, **kwargs)
2024-06-25T16:31:40.373017+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373017+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/newrelic/hooks/framework_django.py", line 558, in wrapper
2024-06-25T16:31:40.373017+00:00 app[web.2]:     return wrapped(*args, **kwargs)
2024-06-25T16:31:40.373017+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373018+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
2024-06-25T16:31:40.373018+00:00 app[web.2]:     return self.dispatch(request, *args, **kwargs)
2024-06-25T16:31:40.373018+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373018+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
2024-06-25T16:31:40.373019+00:00 app[web.2]:     return bound_method(*args, **kwargs)
2024-06-25T16:31:40.373019+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373019+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
2024-06-25T16:31:40.373019+00:00 app[web.2]:     response = view_func(request, *args, **kwargs)
2024-06-25T16:31:40.373019+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373020+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/auth/views.py", line 147, in dispatch
2024-06-25T16:31:40.373020+00:00 app[web.2]:     return super().dispatch(request, *args, **kwargs)
2024-06-25T16:31:40.373020+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373020+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/newrelic/hooks/framework_django.py", line 943, in wrapper
2024-06-25T16:31:40.373021+00:00 app[web.2]:     return wrapped(*args, **kwargs)
2024-06-25T16:31:40.373021+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373021+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
2024-06-25T16:31:40.373021+00:00 app[web.2]:     return handler(request, *args, **kwargs)
2024-06-25T16:31:40.373021+00:00 app[web.2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373022+00:00 app[web.2]:   File "/app/authentication/views.py", line 50, in get
2024-06-25T16:31:40.373022+00:00 app[web.2]:     return redirect(self._keycloak_logout_url(user))
2024-06-25T16:31:40.373022+00:00 app[web.2]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373022+00:00 app[web.2]:   File "/app/authentication/views.py", line 34, in _keycloak_logout_url
2024-06-25T16:31:40.373022+00:00 app[web.2]:     id_token = user_social_auth_record.extra_data.get("id_token")
2024-06-25T16:31:40.373022+00:00 app[web.2]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-25T16:31:40.373023+00:00 app[web.2]: AttributeError: 'NoneType' object has no attribute 'extra_data'
```
### Steps to Reproduce

1. login as superuser on a live environment
2. hijack a user via django admin
3. attempt to logout and witness the 500

### Possible Solution
Error handling around the edge case where user_social_auth_record is None

**Comment by pdpinch** [comment]
@shanbady @sovsey can this be closed?

**Comment by sovsey** [comment]
@pdpinch I closed it a few weeks ago (it's marked as Done). Is it showing up somewhere it shouldn't?
