### ISSUE TITLE
Authentication: Infrastructure configuration for keycloak settings

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mit-open#22]
#### Summary

Describe where/how to generate these new values

- `NEW_ENV_VAR_1` - Describe how/where to get this value
- `NEW_ENV_VAR_2` - Describe how/where to get this value

#### Applicable Environments

- [ ] Apply configuration to CI
- [ ] Apply configuration to RC
- [ ] Apply configuration to Production

**Comment by shaidar** [comment]
Configured `sso-ci` with client that can be used for local dev. This ties into the work that Collin has done https://github.com/mitodl/mit-open/pull/35, but we decided to keep local dev testing limited to the CI env and tie the QA Heroku app with `sso-qa`

**Comment by shaidar** [comment]
With the Heroku QA app now deployed after this PR https://github.com/mitodl/mit-open/pull/43 was merged, I setup a OIDC client and added the necessary config vars to the Heroku app https://github.com/mitodl/salt-ops/pull/1580. When visiting, https://mit-open-rc.odl.mit.edu/login/ol-oidc, I am redirected to the `sso-qa` and after successfully logging in, the Heroku app is throwing a 500 error. Below is the stracktrace for it:
```
2023-08-25T18:42:42.357287+00:00 app[web.1]: [2023-08-25 18:42:40] ERROR 43 [django.request] log.py:241 - [f3d3b7a3-ad64-4c0c-b18d-64015d54c044] - Internal Server Error: /complete/ol-oidc/
2023-08-25T18:42:42.357299+00:00 app[web.1]: Traceback (most recent call last):
2023-08-25T18:42:42.357299+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/utils.py", line 253, in wrapper
2023-08-25T18:42:42.357300+00:00 app[web.1]: return func(*args, **kwargs)
2023-08-25T18:42:42.357300+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357300+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/backends/oauth.py", line 415, in auth_complete
2023-08-25T18:42:42.357301+00:00 app[web.1]: response = self.request_access_token(
2023-08-25T18:42:42.357301+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357301+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/backends/open_id_connect.py", line 236, in request_access_token
2023-08-25T18:42:42.357302+00:00 app[web.1]: response = self.get_json(*args, **kwargs)
2023-08-25T18:42:42.357302+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357302+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/backends/base.py", line 250, in get_json
2023-08-25T18:42:42.357303+00:00 app[web.1]: return self.request(url, *args, **kwargs).json()
2023-08-25T18:42:42.357303+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357304+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/backends/base.py", line 246, in request
2023-08-25T18:42:42.357304+00:00 app[web.1]: response.raise_for_status()
2023-08-25T18:42:42.357304+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
2023-08-25T18:42:42.357305+00:00 app[web.1]: raise HTTPError(http_error_msg, response=self)
2023-08-25T18:42:42.357305+00:00 app[web.1]: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://sso-qa.odl.mit.edu/realms/olapps/protocol/openid-connect/token
2023-08-25T18:42:42.357305+00:00 app[web.1]:
2023-08-25T18:42:42.357306+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2023-08-25T18:42:42.357306+00:00 app[web.1]:
2023-08-25T18:42:42.357307+00:00 app[web.1]: Traceback (most recent call last):
2023-08-25T18:42:42.357307+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
2023-08-25T18:42:42.357307+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-08-25T18:42:42.357308+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357308+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
2023-08-25T18:42:42.357308+00:00 app[web.1]: return callback(request, *args, **kwargs)
2023-08-25T18:42:42.357308+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357309+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
2023-08-25T18:42:42.357309+00:00 app[web.1]: response = view_func(request, *args, **kwargs)
2023-08-25T18:42:42.357309+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357309+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
2023-08-25T18:42:42.357309+00:00 app[web.1]: return view_func(*args, **kwargs)
2023-08-25T18:42:42.357310+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357310+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_django/utils.py", line 46, in wrapper
2023-08-25T18:42:42.357310+00:00 app[web.1]: return func(request, backend, *args, **kwargs)
2023-08-25T18:42:42.357310+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357311+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_django/views.py", line 30, in complete
2023-08-25T18:42:42.357311+00:00 app[web.1]: return do_complete(
2023-08-25T18:42:42.357311+00:00 app[web.1]: ^^^^^^^^^^^^
2023-08-25T18:42:42.357312+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/actions.py", line 49, in do_complete
2023-08-25T18:42:42.357312+00:00 app[web.1]: user = backend.complete(user=user, *args, **kwargs)
2023-08-25T18:42:42.357312+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357312+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/backends/base.py", line 39, in complete
2023-08-25T18:42:42.357312+00:00 app[web.1]: return self.auth_complete(*args, **kwargs)
2023-08-25T18:42:42.357312+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357313+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/utils.py", line 258, in wrapper
2023-08-25T18:42:42.357313+00:00 app[web.1]: raise AuthForbidden(args[0])
2023-08-25T18:42:42.357313+00:00 app[web.1]: social_core.exceptions.AuthForbidden: Your credentials aren't allowed
2023-08-25T18:42:42.357313+00:00 app[web.1]:
2023-08-25T18:42:42.357313+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2023-08-25T18:42:42.357314+00:00 app[web.1]:
2023-08-25T18:42:42.357314+00:00 app[web.1]: Traceback (most recent call last):
2023-08-25T18:42:42.357314+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-08-25T18:42:42.357314+00:00 app[web.1]: response = get_response(request)
2023-08-25T18:42:42.357314+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357314+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/core/handlers/base.py", line 199, in _get_response
2023-08-25T18:42:42.357315+00:00 app[web.1]: response = self.process_exception_by_middleware(e, request)
2023-08-25T18:42:42.357315+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357315+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
2023-08-25T18:42:42.357319+00:00 app[web.1]: response = middleware_method(request, exception)
2023-08-25T18:42:42.357319+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357320+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/sentry_sdk/integrations/django/middleware.py", line 111, in sentry_wrapped_method
2023-08-25T18:42:42.357320+00:00 app[web.1]: return old_method(*args, **kwargs)
2023-08-25T18:42:42.357320+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357320+00:00 app[web.1]: File "/app/authentication/middleware.py", line 37, in process_exception
2023-08-25T18:42:42.357321+00:00 app[web.1]: url = self.get_redirect_uri(request, exception)
2023-08-25T18:42:42.357321+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357321+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_django/middleware.py", line 69, in get_redirect_uri
2023-08-25T18:42:42.357321+00:00 app[web.1]: return strategy.setting("LOGIN_ERROR_URL")
2023-08-25T18:42:42.357321+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357321+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_core/strategy.py", line 48, in setting
2023-08-25T18:42:42.357321+00:00 app[web.1]: return self.get_setting(name)
2023-08-25T18:42:42.357322+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357322+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/social_django/strategy.py", line 45, in get_setting
2023-08-25T18:42:42.357322+00:00 app[web.1]: value = resolve_url(value)
2023-08-25T18:42:42.357322+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357322+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/shortcuts.py", line 145, in resolve_url
2023-08-25T18:42:42.357322+00:00 app[web.1]: return reverse(to, args=args, kwargs=kwargs)
2023-08-25T18:42:42.357322+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357323+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
2023-08-25T18:42:42.357323+00:00 app[web.1]: return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
2023-08-25T18:42:42.357323+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-25T18:42:42.357323+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
2023-08-25T18:42:42.357323+00:00 app[web.1]: raise NoReverseMatch(msg)
2023-08-25T18:42:42.357324+00:00 app[web.1]: django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
```

**Comment by shaidar** [comment]
Turned out that the issue was related to pillar not rendering as expected and so the OIDC client_secret was not set. After addressing that issue, I was able to successfully login to the QA app through Keycloak.
